### ISSUE TITLE
The future are Web Extensions

### ISSUE THREAD

**Issue by rugk** [kee-org/keepassrpc#1]
The current plan is that Firefox 57 will only support [web extensions](https://wiki.mozilla.org/WebExtensions). Your add-on is not a web extension yet as far as I can see, so you should consider remaking your add-on. The Firefox 57 release is [planned for 28th November 2017](https://wiki.mozilla.org/RapidRelease/Calendar).
Already for Firefox 53 (planned release: 18th April 2017) it is planned to no longer accept other new add-on submissions than web extensions on AMO (addons.mozilla.org). Old extensions can however still be updated.
The good message is that one should be able to use your web extensions add-on in all mayor browsers. That's the idea behind web extensions.
Note that you can use so-called [hybrid extensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) for switching to WebExtensions.

Note that all dates are estimates and may be changed.

German source: https://www.soeren-hentzschel.at/firefox/firefox-57-mit-exklusiver-webextension-unterstuetzung/
Original source: https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/

**Comment by dlech** [comment]
http://keefox.org/news/detail/2017/03/26/changes-to-keefox-in-2017

https://github.com/kee-org/browser-addon
