### ISSUE TITLE
One click password generation as in old version would be nice

### ISSUE THREAD

**Issue by gloggerS** [kee-org/keepassrpc#106]
Hi everyone,
in the current version, it takes quite long to generate a new password when signing up for a new webservice. Click on Add-On, Click on Plus, click on flash, choose password profile, click on copy to clipboard, click ok, ...
For me personally, a one click password generation with the default profile and copy to clipboard would be ideal. 
Thanks already for considering 👍 
Best regards,
Stefan

**Comment by luckyrat** [comment]
There is also an option to use the standalone password generator in Kee (e.g. from the context menu or keyboard shortcut) but this isn't an issue specific to the KeePassRPC plugin. In future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just added a GitHub issue template to make that clearer for people arriving at this repo from routes that don't already mention that).
