### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Topkek-190** [kee-org/keepassrpc#115]
Literally. 
Installed the extension. 
Downloaded the plugin and put it into required folder.
Started KeePass. Nothing.
According to the guide, there should've been a popup, but nothing happens and the extension still has the off sign.

KeePass 2.45
KeePassRPC 1.14.0
Kee 3.5.19

**Comment by luckyrat** [comment]
Please ask for support on the community forum: https://forum.kee.pm
