### ISSUE TITLE
Storage of KeePassRPC authorised clients

### ISSUE THREAD

**Issue by moerkey** [kee-org/keepassrpc#117]
Hello,

I am syncing my Thunderbird profile to between to clients (Ubuntu 18.04, Thunderbird 68.10.0, KeePass 2.45, KeeBird 2.0.0, KeePassRPC 1.3.0).

Quite some time ago both clients are asking for a new authorization to access KeePass everytime I start Thunderbird.

There is only one Thunderbird instance running at the same time.
The sync is running fine. There are no corrupted files.

Can you tell me where the auth data of authorised clients is stored in?
I can see that this info is not synced. I want to know which file I am missing.

Ref: https://github.com/kee-org/keebird/issues/31

Cheers

**Comment by luckyrat** [comment]
If you're still having this issue, please use the [Kee community forum](https://forum.kee.pm/). There have been other discussions relating to syncing Mozilla profiles so hopefully something on the forum will already help. In future, using the community forum will likely result in faster help (I've just added a GitHub issue template to make that clearer for people arriving at this repo from routes that don't already mention that).
