### ISSUE TITLE
KeePassXC 2.6.2 crashes

### ISSUE THREAD

**Issue by RolandSM** [kee-org/keepassrpc#118]
Hello,

since few weeks I see unlocated crashes with KeePassXC 2.6.2 on my Kubuntu 20.0.4.1

I have reviewed and see the errors on specific websites, INDEPENDENT if I use Chrome or Firefox...
The website is running a latest PHPMyAdmin page.

I have following testing steps, with which this issue can be reproduced:

1. open a terminal and view the syslog like "tail -f /var/log/syslog"
2. open keepass and login
3. open firefox or chrome and load the phpmyadmin login page
4. keepass crahs and close its window, but background process "pgrep kee" runs
5. in syslog a "general protection fault" comes or sometimes a "segfault at xxx ip xxx sp xxx error 4 in keepassxc

Other ways.
1. You can also prepare a browser with more tabs
2. open with closed keepass the phpmyadmin page and in other pages some others
3. switch active tab to another as phpmyadmin
4. Open KeePass and login.
5. Ensure the browser pugin is connected.
6. Switch the tabs to the phpmyadmin and again the crash.

**Comment by dlech** [comment]
This is repository is for KeePassRPC, not KeePassXC. Try https://github.com/keepassxreboot/keepassxc.

**Comment by RolandSM** [comment]
Ups sorry...
