### ISSUE TITLE
keepassrpc not up to date

### ISSUE THREAD

**Issue by hublex** [kee-org/keepassrpc#120]
Is there a version up to date?

**Comment by dlech** [comment]
Did you check https://github.com/kee-org/keepassrpc/releases?

**Comment by Dimas-sc** [comment]
The last one (1.14) it's not compatible with KeePass 2.47 😢

**Comment by mestan** [comment]
I'm having the same issue. The Kee Chrome extension does not connect with KeePass 2.47 with the KeePassRPC plugin.

**Comment by markuszeller** [comment]
I do experience, too, there is no more communication between browser extension and KeePass2.47.

**Comment by gnorg** [comment]
Same thing here 🖐
I tried reinstalling the Kee extension and KeePassRPC, but the authorisation prompt never appeared on either side.
My (hopefully temporary) solution was downloading KeePass 2.46 again ([https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.46/](https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.46/)).

**Comment by markuszeller** [comment]
Works again. I think the web extension (v. 3.7.8) has been fixed.

**Comment by roadster31** [comment]
Hello ! 

KeePass 2.48.1 is out, and KeePassRPC is not up to date.

**Comment by dlech** [comment]
No update should be needed. See https://github.com/kee-org/keepassrpc/issues/123#issuecomment-840774559.

**Comment by luckyrat** [comment]
There are no known incompatibilities with recent KeePassRPC and KeePass versions so the solution likely lies with making other changes to your system. If you're still having trouble, please see the [Kee community forum](https://forum.kee.pm/), especially the [Troubleshooting](https://forum.kee.pm/t/troubleshooting/560) documentation.
