### ISSUE TITLE
Thunderbird conection broken

### ISSUE THREAD

**Issue by ghost** [kee-org/keepassrpc#121]
I'm on the release channel of Thunderbird.
They decided to release version 78 and I foolishly accepted the update.
Now I'm stuck with a version that has a terrible "upgraded" interface and no connection to KeePass because they don't support rolling back to a previous version (68). (You learn the hard way...)
Some people have done it, but I understand it's painful.

Also, I am seeing the attached recommendation every time I open KeePass.
I know. I should change the password regularly...
But I would prefer the recommendation to be something that is visible but not intrusive on the entry sequence. A n improvement would be a message panel to display warnings and recommendations.

Digging me out of the hole Thunderbird put me in would be appreciated.

![image](https://user-images.githubusercontent.com/75643090/101407385-eb117200-392e-11eb-91b0-98ad1202407e.png)

**Comment by luckyrat** [comment]
The message displayed is unrelated to KeePassRPC. If you're still having trouble specific to KeePassRPC, please use the [Kee community forum](https://forum.kee.pm/) and provide more information so others can help progress this.
