### ISSUE TITLE
Incompatibility with the current version of Keepass (2.48.1)

### ISSUE THREAD

**Issue by xaozai** [kee-org/keepassrpc#123]
![Снимок экрана_2021-05-13_21-50-58](https://user-images.githubusercontent.com/8542452/118172913-9cb05400-b435-11eb-8792-297a1ae98115.png)

Could you please update the plugin.

**Comment by dlech** [comment]
Usually, this is not a problem with the plugin but rather something else.

- Did it work with previous versions of KeePass? 
- Did you install `mono-complete`? 
- What is the output if you run `keepass2 --debug` in a terminal? 
- Are you sure you don't accidentally have two copies of the pluin installed?

**Comment by xaozai** [comment]
The issue was resolved by updating mono-complete. Thanks!
