### ISSUE TITLE
keepassrpc version information file cannot be downloaded

### ISSUE THREAD

**Issue by marcelser** [kee-org/keepassrpc#128]
KeePass keeps reporting KeePassRPC outdated from time to time because it's the only plugin which shows a red cross instead of green check mark or an update sign. It says "update check failed, Version information file cannot be downloaded". I've just updated KeePassRPC to latest 1.14 from forum but it's still showing this in latest KeePass 2.52 (probably also with previous versions). I guess you should fix the version info file location.

**Comment by luckyrat** [comment]
I can't reproduce this issue. Probably it was a temporary internet fault with GitHub or your local connection. If it keeps happening maybe check out firewall or network device logs to find out what is blocking access to the version information file.
