### ISSUE TITLE
KeePass 2.53 (64-bit) craches on Startup Windows 10

### ISSUE THREAD

**Issue by kpleines** [kee-org/keepassrpc#129]
Each time I try to login to the KeePass Database keepass crashes because of an Windows excepteion "Ausnahmeinformationen: System.InvalidOperationException".

Keepaaa 2.53
KeePassRpc 1.14
Windows 10 .NET 7

[Downloads.zip](https://github.com/kee-org/keepassrpc/files/10475286/Downloads.zip)

**Comment by luckyrat** [comment]
There's nothing in this issue description that indicate the crash has anything to do with KeePassRPC so please check out the KeePass support forum - https://sourceforge.net/p/keepass/discussion/

If you're still having trouble specific to KeePassRPC, please see the [Kee community forum](https://forum.kee.pm/) and provide more information.
