### ISSUE TITLE
Update FindAuthorisedConnections for KeePass 2.54

### ISSUE THREAD

**Issue by luckyrat** [kee-org/keepassrpc#133]
Something has changed in v2.54 which causes this method to return null. We need to investigate the cause and develop a new approach that works for that version as well as older ones.

Until then, it is not possible to manage the list of authorised connections.

**Comment by prof-tech** [comment]
I thought that I was unable to authorize the connection from Edge (because it kept popping up). After a bit of trial-and-error I discovered the authorization was working. I still am seeing the error about not being able to manage the connection(s) but KeePass seems fine otherwise. I'm running Dot-Net 6.

**Comment by Pebberman** [comment]
Kee is showing "off", no interaction with keepass, no options,, no Connections

KeePass 2.54 64bit
Kee 3.10.10
Firefox 113.0.2 64bit, same for 114.0

**Comment by brainz80** [comment]
@luckyrat Is it true latest KeepassRPC uses .NET Framework 4.5 - that I believe is deprecated ? Could the reason for the "Authorised clients" -tab no longer working be that KeepassRPC is using a old and deprecated version of .NET Framework ... and perhaps just updating to a newer would help?

**Comment by luckyrat** [comment]
@brainz80 v4.5 is the earliest that we support, not the latest. So this should not be the cause of this issue. I think I have resolved the problem and need to run some more tests and finish up some additional overdue improvements before releasing a new version of the plugin for testing. I'll post an update on this issue soon.

**Comment by luckyrat** [comment]
Please can you try out this pre-release plgx: https://github.com/kee-org/keepassrpc/releases/tag/v1.15.0

That fixes the issue for me.

**Comment by Geexp** [comment]
Thanks @luckyrat just copied over the new version and the "Authorised Clients" tab is working again.
