### ISSUE TITLE
KeePassRPC (and browser plugins as well) should offer/support HTML autocomplete attribute

### ISSUE THREAD

**Issue by typoworx-de** [kee-org/keepassrpc#141]
KeePassRPC (and respectively the browser plugins for chrome/firefox) should offer/support HTML autocomplete attribute additionally to the existing Form-Field definitions. W3C defines to use autocomplete-attributes for form-fields and username/password as well. These input-attributes are a direct hint for password-managers where are the login fields. For newer Web-Frameworks sometimes only these attributes give a hint for the purpose of an input-field. So it's impossible to determine them automatically using existing form-field attributes like id or class-name.

Additionally it would be awesome to allow adding custom-attributes as well.

Simple use-case: have a look at twitter-login!

**Comment by wschlich** [comment]
I've stumbled over the following input field of a form without a `password` field (many sites tend to use 2-step login processes nowadays where you have to enter your username alone in the first step):
```
<input _ngcontent-wxh-c219="" formcontrolname="email" type="email" autocomplete="email" placeholder="Email address" class="no-animate form-control ng-pristine ng-invalid ng-touched">
```
Currently, the Kee browser plugin doesn't offer a way to actually identify this input field for autofilling usernames :-(
If it would support the `autocomplete` attribute, all would be fine indeed!

**Comment by luckyrat** [comment]
We may or may not add support for defining an autocomplete attribute requirement on an entry within KeePass. I'm not currently convinced it would be useful but am open to further discussion a) on https://forum.kee.pm and b) after implementation of automatic autocomplete support in Kee beyond the existing support for "new-password".

As such I'll close this issue now but feel free to continue discussion on the forum and/or track progress of the client implementation: https://github.com/kee-org/browser-addon/issues/337
