### ISSUE TITLE
Placeholder field not replaced in browser when updating to keepassrpc version 2

### ISSUE THREAD

**Issue by CennoxX** [kee-org/keepassrpc#147]
When updating to version 2, the setting at KeePass > File > Database Settings… > Kee > KeePass placeholders > Enable is not respected. I'll have to specifically enable KeePass placeholders also for the individual form fields, otherwise the browser addon only shows something like {TIMEOTP} instead of the numbers. When I enable KeePass placeholders also for the individual form fields, it works again.
![grafik](https://github.com/kee-org/keepassrpc/assets/6975881/4efc6085-3c40-4529-a5b4-a23594d656a0)

**Comment by luckyrat** [comment]
Fix included in https://github.com/kee-org/keepassrpc/releases/tag/v2.0.2 which I'll leave in beta testing for around a week. Please confirm that has solved the issue for you.

**Comment by CennoxX** [comment]
Thanks, the release fixes the issue.
