### ISSUE TITLE
No access to "KPRPC JSON" string field

### ISSUE THREAD

**Issue by YoNevelt** [kee-org/keepassrpc#150]
I'm seeking some explanation here about the below described phenomena.
As a matter of curiousness, I was wondering of the content of the "KPRPC JSON" string but suddenly after installing the latest release, I can't edit nor copy the value of it. Why is this? I feel like I should have full access to everything in my own database. Is this some kind of restriction from this plug-in? I found a workaround to see the content but I don't think this should happen.
I also noticed the symptom of something changes things in the records as described in #149. I think the updated version raises some questions.

**Comment by numericOverflow** [comment]
I'm struggling with the same issue.

In the past, I could update the Kee settings in one entry, get auto-fill working, then copy those settings to additional entries for the same website (when you might have multiple accounts on the same platform, ie work, personal, other users sharing PW database, etc).

Now after moving to KPRPC 2.X, I can't directly manipulate the Kee plugin data, which is a huge step backwards. 

Are there plans to provide a way to manipulate the Kee data going forward, or what's the strategy on the move from string fields to this proprietary/hidden storage mechanism?

**Comment by luckyrat** [comment]
See https://forum.kee.pm/t/questions-about-change-of-plugin-data-storage-in-keepassrpc2/4582

**Comment by YoNevelt** [comment]
Thank you for the detailed explanation.

**Comment by numericOverflow** [comment]
Agree, thank you!
