### ISSUE TITLE
 Add support for String field Placeholders in Form Fields

### ISSUE THREAD

**Issue by mrmeszaros** [kee-org/keepassrpc#17]
Currently Form Fields only supports the base Place holders, like `{USERNAME}`, `{PASSWORD}` or `{URL}`.

However, in KeePass2 the user has the ability to add custom fields (for logins that need more inputs than just user + pass).

Add the support for custom field placeholders. Eg.:
When adding a String field `thing` with some value the placeholder `{S:thing}` should send the value assigned to that field.

**Comment by neradpeter** [comment]
I vote for this tooo

**Comment by luckyrat** [comment]
This is already supported for most custom fields. #30 will also enable it for custom Text fields.
