### ISSUE TITLE
Auto save on opening KeePass and synchronizing problem

### ISSUE THREAD

**Issue by kwomba** [kee-org/keepassrpc#19]
I have KeePassRpc and Kee 2.0.0.25 installed (with KeePass 2.37)
I have a trigger that triggers on "Saving the database". 
Now everytime i open the database this trigger fires (don't know why but this is due to installing KeePassRpc). I think this is a problem.

Moreover this trigger does a synchronize with another database, and whenever a synchronize is executed, the connection with Kee is lost (Kee says: You are not logged in to your password database. Login to your KeePass database to enable Kee) but i am still logged in to my password database (although it has been closed and opened automatically by the synchronize i think).

This way, the Combination of KeePassRps and Kee in not workable which is a real shame.

**Comment by kwomba** [comment]
B.t.w. i have all options in the General section of the KeePassRpc plugin unchecked, i thought maybe some of these would trigger the "Saving the database" trigger to fire.

**Comment by luckyrat** [comment]
Can you disable the trigger temporarily? The only thing that comes to mind here is that some databases with old configurations can be automatically updated when the database is first opened. It should be a one-time event though.

If you're still having problems perhaps you can ask for help on the [community forum](https://forum.kee.pm) and see if anyone else can offer any hints.

This doesn't look like it's an issue with the KeePassRPC code so unless we discover something surprising in later forum discussions, I'll keep this issue closed.
