### ISSUE TITLE
Not working on linux - newer .Net Framework required

### ISSUE THREAD

**Issue by Aetf** [kee-org/keepassrpc#2]
I just downloaded and tried the 1.7.1 version of keepassrpc, but it fails to load in keepass, with the error says: A newer .Net Framework is required to load the plugin.

I'm running Archlinux with reasonable recent version of mono installed (5.0.0, released in May 2017).

**Comment by luckyrat** [comment]
Ugh. Visual Studio has been clever again and duplicated the post build step in the csproj file. I didn't notice so now it's built the plugin using an older process which limits support to .net 4.5+ (which apparently doesn't allow Mono).

Does 1.7.0 work?

**Comment by Aetf** [comment]
Yeah, 1.7.0 works fine. I've been using it without problem for a while.

**Comment by luckyrat** [comment]
Cool. Thanks for letting me know. https://github.com/kee-org/keepassrpc/releases/tag/v1.7.2 should work. Fancy giving it a try?

**Comment by Aetf** [comment]
Works like a charm! 👍 Thanks for quick fix 🎉
