### ISSUE TITLE
FormatException on empty "Page" form field --> Keepass crashes

### ISSUE THREAD

**Issue by Wonno** [kee-org/keepassrpc#20]
How to reproduce:

1. Launch **KeePass** (haha)
2.  _Create_ or _edit_ an entry
3. Navigate to tab "**Kee**"
4. Choose tab "**Form fields**"
5. _Add_ or _Edit_ a form field
6. Set "**page**" to empty
7. Crash Keepass by clicking **OK**

Stacktrace:

`
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei KeePassRPC.Forms.KeeFoxFieldForm.button1_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

KeePass
    Assembly-Version: 2.34.0.15991.
    Win32-Version: 2.34.0.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe.
----------------------------------------
KeePassRPC
    Assembly-Version: 2.0.34.32449.
    Win32-Version: 1.7.3.0.
    CodeBase: file:///C:/Users/anotherUser/AppData/Local/KeePass/PluginCache/20NwuALRHAYN68GcOgZD/KeePassRPC.dll.
`

**Comment by luckyrat** [comment]
Will be fixed in KeePass 1.8. Thanks for reporting it @Wonno
