### ISSUE TITLE
File KeePassRPC 7.1.3 no compatible wtih my Keepass2 2.32, 2.37 or 2.38

### ISSUE THREAD

**Issue by Maiden65** [kee-org/keepassrpc#21]
I have a computer in Ubuntu server 16.04 with LXDE.
I installed Keepass 2.32 with apt and upgrade to 2.37.
I put the file KeePassRPC in directory Plugins 
but when I start Keepass2 I have an error : The file RPC is not compatible with this keepass version...

Can I have a help for resolve my issue ??

**Comment by dlech** [comment]
Sounds like #7

**Comment by Maiden65** [comment]
Thank's
I installed mono-complete but the same issue 
Now, I've 3 popups !! :(
another idea ??

**Comment by Maiden65** [comment]
Sorry, I've 3 popups because I've installed 2 files in main directory and a directory plugins and Plugins :s 
Do I reboot the computer ?

**Comment by nailyk-fr** [comment]
Had the same issue some weekgs ago. 
The required package is not into -complete anymore. 
IIRC list is on the FAQ, or linked on the FAQ. 
Maybe https://github.com/kee-org/KeeFox/issues/148#comment-17441227 can help you too. 
Some internet search should help you quickly too. 
Good luck. 

Le 30 mars 2018 20:58:14 GMT+02:00, Maiden65 <notifications@github.com> a écrit :
>Sorry, I've 3 popups because I've installed 2 files in main directory
>and a directory plugins and Plugins :s 
>Do I reboot the computer ? 
> 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kee-org/keepassrpc/issues/21#issuecomment-377596833

-- 
Envoyé de mon appareil LineageOS avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Maiden65** [comment]
Thank Nailyk
I unistalled mono-complete / reboot computer /install mono-dmcs
the version "mono" actually is 
 Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
And I have already message !!
another idea ?

**Comment by Maiden65** [comment]
YEAH !!!!
Now It's ready. 
The solution for my issue has been : 
1/ Install Keepass2 package ubuntu server : apt install keepass2 ==> version 2.32
2/ upgrade Keepass version to 2.37 : download zip file et unzip file in directory /usr/lib/keepass2
3/ install mono composants : apt install mono-mcs libmono-system-management4.0-cil libmono-system-configuration-install4.0-cil libmono-system-numerics4.0-cil
4/ execute command mono keepass.exe

To the first connect KEE (firefox) I have the pwd for connection to the database Keepass.

Now, I tested using my passwords imported and it's OK

Very thank's for your help !!!
