### ISSUE TITLE
KeeWeb compatibility

### ISSUE THREAD

**Issue by KINFOO** [kee-org/keepassrpc#25]
Hi,

I just tried https://keeweb.info, as I am using [Kee with Firefox](https://addons.mozilla.org/fr/firefox/addon/keefox): I tried to install `keepassrpc` in `KeeWeb` to enable [Kee in Firefox](https://addons.mozilla.org/fr/firefox/addon/keefox).

![KeeWeb Plugins](https://user-images.githubusercontent.com/154818/38819749-82c352ea-419c-11e8-8271-8de9822b65c5.png)
> `keepassrpc` is not available in list

![KeeWeb manual install](https://user-images.githubusercontent.com/154818/38819886-e51b0d0c-419c-11e8-8b17-57da242be99e.png)

`KeeWeb` states it is not able to load _plugin manifest_.
Reading [Plugin manifest documentation](https://github.com/keeweb/keeweb/wiki/Plugins), I realize `KeeWeb` is not compatible to `C#`. It only mentions [JS](https://github.com/keeweb/keeweb/wiki/Plugins#plugin-contents).

All this being said, do you think `KeeWeb` integration is possible?

Thanks for your work

**Comment by luckyrat** [comment]
I've recently [announced Kee Vault](https://forum.kee.pm/t/kee-vault-and-kee-version-3-0/2025), which has a visible interface that is based upon KeeWeb. It comes with built-in support for the Kee browser extension. It utilises a similar link to the one with KeePass but runs entirely within the web browser so I've been able to develop a solution that doesn't rely upon the existing C# plugin.

As you've probably already realised, getting this C# plugin to work in KeeWeb can't happen so I'll close this issue now as being out of scope for this project.
