### ISSUE TITLE
Parameter for Listen Address

### ISSUE THREAD

**Issue by florian-asche** [kee-org/keepassrpc#28]
Hi,

i want to use one KeePass RPC Instance across multiple (two) computers. Is this by design possible?
If yes, the listen address needs to be configureable. For example localhost (127.0.0.1) or 0.0.0.0 ...

**Comment by luckyrat** [comment]
KeePassRPC has been designed primarily with local connectivity in mind. There are *probably* no critical security risks of opening the connection more widely but as described in the [draft release notes for v 1.8](https://github.com/kee-org/keepassrpc/releases/tag/v1.8.0) there is always a small risk of social engineering attacks, and denial of service attacks can't be ruled out either.

For that reason, I won't consider opening up this for configuration. You could modify the code yourself but most likely you'll find that using a port proxy with something like Putty/SSH is easier and more secure. I've never tried it myself but probably some people on the [community forum](https://forum.kee.pm) have.

**Comment by florian-asche** [comment]
Ok. Yes, will do that. It's just between a virtual machine and guest system. (Windows OS and Linux VM)
