### ISSUE TITLE
Either KeepassRPC or KeeAgent works

### ISSUE THREAD

**Issue by Nama** [kee-org/keepassrpc#33]
Hi,
since Windows 10, after I start Keepass for the first time after Windows' boot and unlock of the database, Kee works, but KeeAgent don't.
Putty and Filezilla just don't reconigze the Agent.
I close Keepass, start it again and unlock the database. Putty and Filezilla can connect now, but Firefox and Thunderbird do say "Keepass is not running" and aren't autofilling login forms anymore...

Keepass: 2.38
KeepassRPC: 1.8
Kee (Firefox): 2.3.19.1
KeeAgent: 0.10.1.0

Thanks

**Comment by dlech** [comment]
https://github.com/dlech/KeeAgent/issues/230

**Comment by dlech** [comment]
> KeepassRPC: 1.8

~~~This is a rather old version of KeePassRPC. If this is really the version you have, it is not surprising that things are not working.~~~

~~~Please make sure that you have installed the latest version of KeePassRPC and that you don't accidentally have more than one version installed (this can happen if you have multiple subdirectories containing plugins).~~~

**Comment by JanisEst** [comment]
KeePassRPC 1.8 is the current version?
I use both plugins too and I don't have issues.

**Comment by dlech** [comment]
Thanks for the correction. I had it in my head that KeePass RPC was at v2.x for some reason.

**Comment by Sanaki** [comment]
What other plugins do you use? I run both simultaneously on both mono and windows and haven't ever had this issue.

**Comment by Nama** [comment]
Works for me on mono and worked for me on Windows 8.1, too. But it's like this since I use Windows 10.
These are all the plugins:
![skizze](https://user-images.githubusercontent.com/2297270/39600259-7d2093d6-4f1e-11e8-85b6-cff44608962a.png)

**Comment by Sanaki** [comment]
Unless DataBaseBackup or Favicon Downloader are doing something ridiculously stupid (which I doubt), that doesn't seem a likely avenue. I'm migrating away from Windows 10 myself, but right now the only noteworthy difference I see between us there is that I don't use FileZilla, and its presence shouldn't be an issue. I have no issues with putty or Kee/Keefox (in either firefox or thunderbird).

Just to clarify further, I assume KeepassRPC is using the default port still (12546), and KeeAgent is running in agent mode (check through the loaded key list's window title if you're on auto) with default settings intact?

I'll look into filezilla's interaction and see if that could somehow be related. EDIT: No.

**Comment by Nama** [comment]
Yes, KeepassRPC is using the default port and KeeAgent is set to Agent. I double checked that.
I didn't assume Filezilla could interfere somehow.

I used this plugins on Windows 8.1, too. This problem didn't appear.

**Comment by Sanaki** [comment]
Unfortunately, I'm just a user, not someone with familiarity with the code, and at this point I'm out of useful ideas. I tried to find information on how to pull proper debug messages from keepass, but I came up dry on that one (if someone does know, please educate me). Hopefully one of the devs will be able to figure it out.

Just for the sake of frustrated debugging, my only remaining suggestions (ordered from easy to unnecessarily time consuming):
1. Change the port on KeepassRPC and Kee or Keefox, see if somehow a port conflict is to blame.
2. Close keepass, strip all plugins out, then add them back one at a time from most to least relevant and see if the issue has a trigger point in that process. You'll need to close keepass again each time you change plugins around.
3. Check your antivirus/firewall logs (if applicable). Temporarily disable both and test again (disconnect from your network first if you believe it's necessary).
4. Make a dummy database with one entry for Kee to use and one SSH key to load, see if the issue persists in the new database. Make new entries (and a new SSH key preferably), don't copy old ones just in case the flaw lies at one of those points.
5. If you use a portable installation of keepass, try installing it normally, and vice versa if it's installed normally. Hell, you could also make an extra portable installation to check if need be (wouldn't pinpoint a portable-specific issue, but a keepass configuration issue would show this way).
6. Get access to another Windows 10 system, copy your database to that, and see if it's an issue with your specific installation of Windows (if you upgraded from 8.1 directly, who knows what could go funky).
7. (Overkill, don't bother unless you have other reasons to or a lot of free time) Get a spare hard drive [(or a flash drive if you use Windows 10 Enterprise edition)](https://www.pcmag.com/article/352209/how-to-run-windows-10-from-a-usb-drive), swap yours out, install windows 10 fresh on the system (it'll auto-activate as long as your overall hardware hasn't changed), test a fresh installation on the same hardware. There's no reason I can see why a hardware configuration would cause this issue, but I've honestly seen stranger things happen.

It's unlikely any of those will turn something up, but it couldn't hurt to find out, assuming it's worth the time for you.

**Comment by Nama** [comment]
So, finally I could try some things...

> Change the port on KeepassRPC and Kee or Keefox, see if somehow a port conflict is to blame.

I change the port, restart KeePass, Kee connects! I restart KeePass again without changing the port. No connection. I change back to the old port and restart KeePass. It works.
Thats not an solution. Also, this happens with all plugins disabled but KeepassRPC.

> Check your antivirus/firewall logs (if applicable). Temporarily disable both and test again (disconnect from your network first if you believe it's necessary).

I'm using Windows Firewall and Windows Defender. On the ressource monitor KeePass is listening on that port and Firefox has connections to the same port. Firewall status is "not blocked".

> Make a dummy database with one entry for Kee to use and one SSH key to load, see if the issue persists in the new database. Make new entries (and a new SSH key preferably), don't copy old ones just in case the flaw lies at one of those points.
> If you use a portable installation of keepass, try installing it normally, and vice versa if it's installed normally. Hell, you could also make an extra portable installation to check if need be (wouldn't pinpoint a portable-specific issue, but a keepass configuration issue would show this way).

With a fresh configuration KeepassRPC is working. KeeAgent seems to work, too. But since I didn't reboot, I'm not 100% sure.

I also realizied, that a cmd process was persistent after closing KeePass (which I let start via triggers). I removed it and will see how it works.

**Comment by Nama** [comment]
Removing the cmd process from triggers and deactivating the trigger system didn't help.
After login on Windows, Kee works, but KeeAgent don't.
KeeAgent shows the loaded keys, I can lock and unlock and it still wont work.
After one restart of Keepass Kee doesn't work and KeeAgent works...

I have no ideas anymore.

**Comment by Nama** [comment]
I am starting Keepass from a own script via the TaskScheduler and because of another part of it, I let it execute with "higher privileges" - as Administrator. That made KeeAgent not recognizable for all SSH clients.

KeepassRPC/Kee works now mostly after restarting Keepass. I don't know why.
