### ISSUE TITLE
KeePassRPC 1.8.0 does not handle KeePass2 references

### ISSUE THREAD

**Issue by tarrychk** [kee-org/keepassrpc#37]
In KeePass2 you can define references between entries, e.g.
{REF:U@I:DEADBEAFDEADBEAFDEADBEAF} would be a reference to the username field of the entry with ID "DEADBEAFDEADBEAFDEADBEAF", {REF:P@I:DEADBEAFDEADBEAFDEADBEAF} would be a reference to the password field, and so on. You only have to modify the original entry and all other references would pick up the changes automatically.
This works fine with KeePassRPC 1.7.3, but 1.8.0 fills in the reference string verbatim. Downgrade to 1.7.3 resolves the issue for me.

**Comment by tarrychk** [comment]
I was able to reproduce this with KeePass 2.38 on Debian Linux and Windows 10.

**Comment by Jeremate** [comment]
I'm facing the same issue in Windows 7 (KeePass 2.38). Downgrading to 1.7.3 fix the issue.

**Comment by proxymus** [comment]
Have a look at #32. You can enable it per entry or global.

**Comment by luckyrat** [comment]
See https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107
