### ISSUE TITLE
KeePassRPC 1.8.0 Global Placeholder handling is reset to Disable after closing KeePass

### ISSUE THREAD

**Issue by proxymus** [kee-org/keepassrpc#38]
I've noticed that the global placeholder setting is reset to disable when I close the KeePass application.

Steps to reproduce:

1. File -> Database settings -> Kee -> KeePass placeholders
2. click on **enable**
3. click on **OK**
4. close KeePass
5. open KeePass again and start at step 1
6. setting is set back to **Disable**

**Comment by luckyrat** [comment]
You need to save your database after making changes to its settings. KeePass should be asking you to do this when you close it but perhaps you have changed a setting somewhere which prevents that.

**Comment by proxymus** [comment]
I've autosave enabled. The setting isn't saved.

**Comment by luckyrat** [comment]
Sorry, I don't know why that's not working for you. Maybe ask on the [community forum](https://forum.kee.pm) in case someone has any other ideas.

It saves just fine for me whether autosave is enabled or not.

**Comment by gpion** [comment]
Same issue for me, reproductible at will with  two different database,
