### ISSUE TITLE
1.8 Doesn't Properly Use Field References

### ISSUE THREAD

**Issue by AiononOrig** [kee-org/keepassrpc#40]
Just thought I'd let you know I've had to revert to 1.7, and Keepass 2.38 now, because your 1.8 of the RPC breaks usage of field references.  Instead of using the password from the reference, I believe it is putting in the entire text of the reference itself.  Big deal for me, as I have a core account in keepass that stores a single domain password, which is then referenced around to multiple others that all use my domain credentials.  This occurred on another PC when 1.8 first came out, and I reverted and didn't think any more about it.  Just updated Keepass to 2.3.9 on another, and was forced to go to 1.8 there as well, and experienced same issue.  Reverted both and rebuilt plugin cache and working again.

**Comment by r0bb3n** [comment]
I can verify this:
working: KeePassRPC 1.7.3.1 + KeePass 2.38
not working: KeePassRPC 1.8.0 + KeePass 2.38
not working: KeePassRPC 1.8.0 + KeePass 2.39

**Comment by kfmndev** [comment]
I also have this issue while using KeePassRPC 1.8.0 and KeePass 2.39

**Comment by EmTeedee** [comment]
This seems to be a new security feature, which thankfully can be disabled :-)
See https://forum.kee.pm/t/placeholder-handling/1100

**Comment by luckyrat** [comment]
As per the [release notes](https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107), this is by design.
