### ISSUE TITLE
Compatibility issue with KeePass 2.39

### ISSUE THREAD

**Issue by thx1200** [kee-org/keepassrpc#41]
When launching KeePass 2.39 the following error is presented and the plugin does not work.

![image](https://user-images.githubusercontent.com/5454591/39791252-ac107db2-5308-11e8-8d3f-ce4374d61def.png)

**Comment by Kryophilos** [comment]
https://github.com/kee-org/keepassrpc/releases/tag/v1.8.0 works for me. Took me a while to discover it, though...

**Comment by zago84** [comment]
I confirm, v1.8.0 works with KeePass 2.39

**Comment by jbwolfegit** [comment]
I am getting the same error on two clients but on one other it works. Attempted reinstall of KeePass 2.39 with no effect. Two are Win7 and one is Win10. I think the plugin is working on all clients despite the error message.

**Comment by accodev** [comment]
I'm getting the same error but as @jbwolfegit mentioned, the plugin works correctly (Keepass v 2.39 and plugin v 1.8.0. I've also tried to clean the plugin's cache to no avail.

**Comment by thx1200** [comment]
I got the error with 1.8.0.  I'll try doing a full uninstall and reinstall, delete everything, and see if that helps.

**Comment by Havokdan** [comment]
1.8 works for me in keepass 2.39.1

**Comment by AJJLagerweij** [comment]
I have the same error on linux (Ubuntu 18.04 with mono) 
![afbeelding](https://user-images.githubusercontent.com/31255888/39970446-e35535c4-56eb-11e8-8ac9-159e6696d73a.png)
It does not work afterwards.

My other device (Windows 10) works like a charm.

**Comment by thx1200** [comment]
OK I upgraded to KeePass 2.39.1, re-downloaded 1.8.0 and it's working for me.  Thank you!

**Comment by slcpunk** [comment]
Hey @AJJLagerweij  - any luck figuring it out for Ubuntu??  I just upgraded to 18.04 - keepass2 is only at 2.38 and I don't see any option or PPA to get to 2.39.  I tried keepassRPC 1.8 and 1.7.3 and neither loaded.

**Comment by AJJLagerweij** [comment]
I run Keepass2 trough mono using the portible_keepass_2.39.1.zib unpack it. I then run it with mono and manually make a desktop launcher file. This used to work well for me, however since the update it keeps crashing on the RPC plug-in.

My currently working solution is using KeePassXC (2.3.1) and use the KeePassXC-Browser exstension. Which works fine. However I would like to use KeePass2 so that I get the same experience on all my devises.

**Comment by slcpunk** [comment]
bummer.  I had been on 16.04 for so long, it just worked with the jtaylor PPA and the RPC plugin updates.   

I do wonder if it is a MONO problem vs. an RPC plugin problem.  Maybe the error message just isn't clear enough.  Always a hassle getting mono to run correctly in Ubuntu.  Too bad keepass2 uses it ... 

I also have a mix of devices and really want to stick with keepass2

thanks for replying!

**Comment by AJJLagerweij** [comment]
Yeah, I'm not sure where the issue is either but the ppa is (currently) not working for me. And the error message (see my post above) does not help me at all. I do not know where to start fixing it.

**Comment by slcpunk** [comment]
hey @AJJLagerweij , I figured it out.  ( really not that smart of me to forget and miss these instructions )
to make it work, install mono-complete.  Then you can use keepassRPC v 1.8 with keepass 2.38.  Works just fine.  I added the mono PPA, not sure if that is required or not.  ( find here: http://www.mono-project.com/download/stable/ )  Good luck.

**Comment by anthonyalvarez** [comment]
[KeePassRPC v1.8.0](https://github.com/kee-org/keepassrpc/releases/tag/v1.8.0) is running at this workstation. I have found that old versions of KeePassRPC in the plugins directory will cause KeePass to generate errors. After they were deleted, my errors disappeared. 

**My System Data**
- Win10x64 Pro
- Version: 1803
- OS Build: 17134.48
- Firefox 60.0.1 (64-bit)

**Comment by accodev** [comment]
@anthonyalvarez thank you very much. Uninstalling KeePass and removing all remaining plugins manually worked! Now KeePass doesn't show that warning window anymore.

**Comment by Sanyy** [comment]
On ubuntu 16.04 i got the same error with Keepass 2.38 like @AJJLagerweij. Close Keepass then the magic command is:

sudo apt-get -y install mono-complete

start Keepass again... & believe in magic.

**Comment by AJJLagerweij** [comment]
Thanks everyone, I indeed forgot to install the complete mono version. Now keepassrpc works with KeePass2 39.1 as well.

**Comment by luckyrat** [comment]
As per the [release notes](https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107), this is expected. Upgrading to 1.8 should resolve the issue, if not, please search on the [community forum](https://forum.kee.pm) since there is already help available there.
