### ISSUE TITLE
Username autocomplete not working with < input type="email" />

### ISSUE THREAD

**Issue by diegoernestofarias** [kee-org/keepassrpc#42]
Username autocomplete not working with < input type="email" />
Example: https://www.mercadolibre.com/jms/mla/lgz/msl/login

**Comment by luckyrat** [comment]
Please search on the [community forum](https://forum.kee.pm) for help. There should be no reason that input fields of type email will not work, and in any case it would be a browser-addon issue, not one for KeePassRPC.
