### ISSUE TITLE
Kee Password Icon Missing

### ISSUE THREAD

**Issue by angrycuban13** [kee-org/keepassrpc#43]
Hi,

I've noticed recently the password icon is missing from certain websites that are in my database. 

If I hover over where the icon usually is, I can press it and select the login if there are multiple logins.

![kee missing icon 4](https://user-images.githubusercontent.com/39564898/40438043-92fc136e-5ea6-11e8-8b06-a1d1215be69b.jpg)
![kee missing icon 2](https://user-images.githubusercontent.com/39564898/40438044-931622ea-5ea6-11e8-9f4a-a8ebcc574b32.jpg)
![kee missing icon 1](https://user-images.githubusercontent.com/39564898/40438045-932cfd3a-5ea6-11e8-9a34-6a462e99d78e.jpg)
![kee missing icon 3](https://user-images.githubusercontent.com/39564898/40438046-9346ec90-5ea6-11e8-85e7-7d53787f852d.jpg)

Some of the websites I've noticed this one:

amazon.com
navyfederal.org
Gmail
USAA

I'm running the latest KeePass version 2.39 and the latest Kee version 1.8.0.0

I'm on Windows 10 v. 1803 OS Build 17134.48

**Comment by luckyrat** [comment]
Please post to the Kee community forum instead (this is not a KeePassRPC issue) but link to this issue if you want for reference. To help further, we would need to know if the problem occurs when you have no other add-ons enabled in your browser and your browser version number. Also, please clarify which version of Kee you are using (I'm assuming KeePassRPC 1.8 from your comment). Do you see a list of matched logins or is it empty as per your screenshots? (I'm not sure if you have just blanked out personal data of if they are accurate representations of what you saw on screen). Does it happen every time you visit those sites?
