### ISSUE TITLE
blacklist inputs by classname

### ISSUE THREAD

**Issue by dbursem** [kee-org/keepassrpc#44]
I'm trying to use Rocketchat which has a smiley input window with a searchfield with name="name" and no id. I'd like to blacklist it using a classname but am kind of surprised I can only use id's and names to blacklist it. 

Could a blacklist on classnames be added?

**Comment by luckyrat** [comment]
This has come up before (probably on the [community forum](https://forum.kee.pm) but possibly pre-dating that) and has been on the wishlist in some form or another for around 7 years. It's unlikely to be a KeePassRPC issue anyway so if you can't find an existing post on the subject, creating a new one on the fourm would be more appropriate.
