### ISSUE TITLE
Keepass 2.39.1 compatible with 1.80

### ISSUE THREAD

**Issue by antuketot76** [kee-org/keepassrpc#46]
Guys, just to inform as below.
KeePass Version       - 2.39.1
Released Version      - [HERE](https://keepass.info/news/n180506_2.39.html)
KeePassRPC Version - 1.80.0

![image](https://user-images.githubusercontent.com/33280865/41155123-b463ad2e-6b57-11e8-818e-939a5f041c2b.png)

**Comment by luckyrat** [comment]
Yep, that version works just fine. Thanks.
