### ISSUE TITLE
Per domain URL match accuracy control in Database Settings part 2

### ISSUE THREAD

**Issue by mnaiman** [kee-org/keepassrpc#48]
Hi,

this settings is not working for me. In Database settings I have set "Hostname".
Each entry(500 entries) doesnt have any "KPRPC JSON" (migrated from other solution).

This code in case of no "KPRPC JSON" takes value of entry.GetKPRPCConfig (new default entry) and ignores dbConf.DefaultMatchAccuracy
https://github.com/kee-org/keepassrpc/blob/0c701cd705f0ccb7b4d78da6eab7b98654b03eea/KeePassRPC/Extensions.cs#L70

Result - it behaves like Database settings set "Domain".
Per entry override works ok

**Comment by luckyrat** [comment]
https://github.com/kee-org/keepassrpc/blob/0c701cd705f0ccb7b4d78da6eab7b98654b03eea/KeePassRPC/Extensions.cs#L72

This nearby line of code applies the per-domain URL match accuracy adjustment. I would expect this to therefore override using the per-domain URL regardless of whether the entry has an existing configuration or not.

However, I'm not in a position to work on the code at the moment to verify this.

I think what we need to do is develop an alternative to the test which assigns a configuration to the entry on this line:
https://github.com/kee-org/keepassrpc/blob/cbbff91ce4e544864eda09e069743b54c9f2dace/KeePassRPCTest/URLMatchTest.cs#L66

If that test fails, we can then investigate why and see what can be done to change it.

If you want to take a look at this yourself feel free (I'll assign this to myself if I'm about to start work on it but don't hold you breath).

Even if the test passes and we find another cause for your problems, it could be worthwhile adding this extra test coverage to the project for protection against future bugs.

**Comment by mnaiman** [comment]
Hi have solved issue.
https://github.com/kee-org/keepassrpc/pull/50

Can you build release? Thx

**Comment by mnaiman** [comment]
Sorry I don't know how to continue - changing of these migration functions presume knowledge of history of config, so I would do make more bugs that bugfix.

I have no KPRPC JSON entries. So I though that when is no KPRPC JSON present it should take MatchAccuracyMethod from global dbConf.DefaultMatchAccuracy.
But even I have dbConf.DefaultMatchAccuracy set to Hostname, it acts like it is set to Domain.

Its clear bug, because description in global dialog states "This affects new entries and entries with NO existing KeePassRPC configuration."

**Comment by luckyrat** [comment]
I've now removed the legacy migration code from 2012 so your suggested fix works a treat. I have created a set of tests to verify the scope of the problem and ensure that it does re-occur. I'll include those tests and your fix in a new commit that resolves this issue in a moment.

Thanks for trying to fix it and sorry that the migration stuff slowed the process down so much.

**Comment by mnaiman** [comment]
@luckyrat Perfect, its working in 1.9 fine - thx 👍
