### ISSUE TITLE
References no longer resolve

### ISSUE THREAD

**Issue by hexd0t** [kee-org/keepassrpc#49]
I recently updated KeepassRPC from the version I installed to use the first Kee 2 Alpha (can't say which one that was exactly) to the current stable due to some hiccups when using Kee. Since then, references in the password field are no longer correctly resolved.

Example:
I have two Systems that use the same password database, but require different things as my user (one requires my email, the other a username).
In the past, I would store the password with the first entry, and then input something like {REF:P@T:System1}, which resolves to the Password stored in the Entry named "System1" (see [https://keepass.info/help/base/fieldrefs.html](https://keepass.info/help/base/fieldrefs.html) for more info).
This has worked with Kee, but now it doesn't. If I check in the browser console, I see kee inserted the reference code without resolving it:
```
> document.getElementById("passwordInput").value
< "{REF:P@T:System1}"
```
Using Ctrl+C in KeePass on the indirect entry does work (e.g. copies the Password of the other entry)

**Comment by suhrmann** [comment]
`KeePass 2.39.1`
`KeePassRPC 1.8.0.0`

This issue is present for the username as well as for the passwords.

_Sample fill suggestions with unresolved references:_
![unbenannt](https://user-images.githubusercontent.com/6432295/41839015-5c6acd6a-7862-11e8-8897-2e6834e45c75.PNG)

**Comment by luckyrat** [comment]
By design, explained in the release notes: https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107
