### ISSUE TITLE
Kee doesn't resolve references

### ISSUE THREAD

**Issue by Poil** [kee-org/keepassrpc#51]
Hi,

A new bug with 1.8.0 (And KeePass 2.39.1), when I copy paste a password that is a reference to another entry {REF:P@I:1C0CADD1DFD4DD4DBD0DBD3D2BD6DD4A}, in KeePass the reference is resolved (the password is copied) but in KeeFox it is no more and {REF:P@I:1C0CADD1DFD4DD4DBD0DBD3D2BD6DD4A} is paste in the input form

Best regards

**Comment by florentin68** [comment]
This seems not to be a bug but a new security.
See explainations here: https://forum.kee.pm/t/placeholder-handling/1100

**Comment by Poil** [comment]
Thanks it's that ... but I think we should allow `{REF:`

**Comment by dlech** [comment]
Duplicate of #32, #37, #40 #47, #49
