### ISSUE TITLE
Keepass 2.40 fails to compile KeePassRPC.plgx

### ISSUE THREAD

**Issue by jtlayton** [kee-org/keepassrpc#59]
When I start keepass 2.40 (under Fedora 29), I get a message saying that KeepassRPC.pglx is incompatible with this version. I ran the program with --debug and got the attached file that shows the plugin failing to compile, mostly with this error:

/run/user/4447/KeePass/D3405741D04556478233EE8D3B1BB265/Forms/KeyCreationSimpleForm.cs(42,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?

[tmp18d3b8f5.txt](https://github.com/kee-org/keepassrpc/files/2438796/tmp18d3b8f5.txt)

**Comment by dlech** [comment]
This was fixed in KeePassRPC 1.8.0. Are you using that version?

**Comment by jtlayton** [comment]
Thought I had updated it but it turned out that I hadn't. It's working now. Sorry for the false alarm.
