### ISSUE TITLE
Plugin not compatible with Keepass2 2.4

### ISSUE THREAD

**Issue by dvictori** [kee-org/keepassrpc#60]
I'm running Ubuntu 18.04 and installed Keepass2 from the following source:
http://ppa.launchpad.net/jtaylor/keepass/ubuntu

The PPA just updated Keepass2 to version 2.4 and now I get a message saying that keepassrpc plugin is incompatible.

**Comment by dlech** [comment]
duplicate of #59, #57, #52, #41, etc.?

**Comment by dvictori** [comment]
Sorry for the noise. Turns out I had removed mono-devel. So the plugin was not compiled correctly after keepass2 update. Closing this issue

**Comment by dvictori** [comment]
Just an update. One thing that threw me off in thinking that keepassrpc was not compatible with Keepass2 v2.4 was that in the [plugin release notes](https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107), it says it's compatible with version 2.39. So maybe updating that description might avoid having people opening unnecessary issues
