### ISSUE TITLE
Blacked out Autorization Window

### ISSUE THREAD

**Issue by girstenbrei** [kee-org/keepassrpc#63]
Hi there!
I have installed: Fedora 29 (Kernel 4.18.17-300), KeePass 2.40 and KeePassRPC 1.8.0.0. There are no compilation errors for the plugin but after opening both Firefox (63.0.3) and KeePass, KeePass opens a new Authorization Window every 3-5 seconds, they look like this:
![bildschirmfoto vom 2018-11-19 09-11-21](https://user-images.githubusercontent.com/22026499/48694259-2c197b00-ebdc-11e8-86bf-84d44f011860.png)
I cannot stop them from opening nor can I enter anything. 
After changing the Connection Security options to 'High' in both fields of the RPC-Options, i get a regular autorization window (with a code) and I can enter it in Firefox, everything works fine then. But I cannot set the security to Medium. Is there any indication what the problem is? Am I doing something wrong? Can I provide you with more information?

Thank you for your wonderful plugin,
Chris

**Comment by luckyrat** [comment]
I've recently added more information about debugging and logs to the [troubleshooting documentation](https://forum.kee.pm/t/troubleshooting/560). Please take a look at that in the first instance (assuming a system/Mono update hasn't already resolved the problem for you) and then post some info on the community support forum if you still need help after that.
