### ISSUE TITLE
KeePassRPC.plgx incompatible message with KeePass 2.41 on Windows 10

### ISSUE THREAD

**Issue by bignis** [kee-org/keepassrpc#64]
I've looked at related open issues, but this one appears to be different.  Upon loading KeePass 2.41 I get:
![image](https://user-images.githubusercontent.com/1821535/50944432-eb104b00-1455-11e9-835f-170c1a40a62d.png)

when I run with -debug flag I see

![image](https://user-images.githubusercontent.com/1821535/50944439-f19ec280-1455-11e9-99a7-aafe6e7b239d.png)

then

![image](https://user-images.githubusercontent.com/1821535/50944443-f5324980-1455-11e9-8117-5e072b00f316.png)

I've attached the .tmp file results, basically it says: "KeyCreationSimpleForm.cs(61,11): error CS0246: The type or namespace name 'SecureEdit' could not be found"

My Windows version
![image](https://user-images.githubusercontent.com/1821535/50944381-b8665280-1455-11e9-9a66-82587dfd1c24.png)
[tmp5551.zip](https://github.com/kee-org/keepassrpc/files/2743489/tmp5551.zip)

**Comment by bignis** [comment]
attachment
[tmp5551.zip](https://github.com/kee-org/keepassrpc/files/2743487/tmp5551.zip)

**Comment by luckyrat** [comment]
This was fixed in KeePassRPC 1.8.0 last year.

**Comment by bignis** [comment]
@luckyrat pardon my lack of knowledge here, as a user of KeePass - how can I get this fix applied to my installation of KeePass?  Is there a way I can "upgrade" to KeePassRPC 1.8.0 for example?

**Comment by dlech** [comment]
https://forum.kee.pm/t/upgrading-keepassrpc/22
