### ISSUE TITLE
Auto generated passwords are ignorred without the users Knowledge

### ISSUE THREAD

**Issue by l1m3r** [kee-org/keepassrpc#66]
It's not really a bug - more a usability issue:
Recently I modified a "Kee generated password at: <date+time>" entry in KeePass to actually make it usable with the website I used the password for.
-> I modifed/added URL, Username and Icon & moved it to another folder in the KeePass db.

But to my surprise the Kee browser addon just ignorred it.
Some try/trial(?) and error later, after closing, re-opening the keepass db, force refreshing the website a few times and fiddling with the URL - I finally found the "Hide this entry from Kee" field in Kee's "Edit Entry" tab.

Suggestion: Supply every auto generated password with a note (in the default note field) informing the user of this feature.

**Comment by luckyrat** [comment]
Good idea.

I'm thinking of making wider changes to the way we save passwords though so lets hold off on this one until we're closer to making a new release in case it becomes obsolete before even being released.

**Comment by luckyrat** [comment]
It'll be a while before I can think about wider changes and I'm planning on releasing a new version of KeePassRPC shortly so I'll solve this issue by following your suggestion of including a note in the entry.
