### ISSUE TITLE
Plugin does not compile on KeePass2 v2.41

### ISSUE THREAD

**Issue by yannham** [kee-org/keepassrpc#68]
Hi,

I try to install a KeeFox on a fresh Debian (unstable) but I can't get the plugin to compile:

![keep](https://user-images.githubusercontent.com/6530104/53799333-11240a00-3f32-11e9-9bdc-6c68d848964b.png)

I just downloaded the RPC file from the link given in the help section (v1.8 tagged latest) so it should be up to date. Any idea ?

**Comment by dlech** [comment]
`sudo apt update && sudo apt install mono-complete`. Check existing issues for more information.

**Comment by luckyrat** [comment]
Or the community forum: https://forum.kee.pm
