### ISSUE TITLE
Plugin incompatible with current version of keepass

### ISSUE THREAD

**Issue by Willzyc** [kee-org/keepassrpc#7]
I am using keepass version 2.36 on linux mint 18.2

Using the rpc plugin I get those errors:

v1.7.1 The known error with the net framework
v1.7.2 and 1.7.3 are incompatible with the version of keepass
"The following plugin is incompatible with the current KeePass version:
/usr/lib/keepass2/plugins/KeePassRPC.plgx"

On my desktop with Ubuntu 16.04 it works fine

**Comment by luckyrat** [comment]
Are you sure you have the right version of KeePass installed? Check the About menu in KeePass.

Failing that, make sure you have mono-complete installed?

**Comment by ioistired** [comment]
Installing mono-complete fixed it for me on KeePass2 v2.35 and 1.7.2 on Ubuntu 17.04 with Mono 4.6.2.

**Comment by cracket** [comment]
This is very problematic on Ubuntu 14.04  (yes - it is supported by April 2018, dont be surprised) - keepass2 ver 2.25 is not loading plgx ver 1.7.3.1

luckyrat has mentioned "the right version" of KeePass - I haven't found any map of supported versions by keepassrpc bound to KeePass versions, and on release page - there is not much about either keepass version or mono version. 

Moreover it would be good to have some compatibility hints between Kee and keepassrpc, otherwise people assume any version of rpc works with any version of plugin and it always will lead to big disappointment. 

Anyway - what I would add to release notes:  hash of plugin, and there is easy way to check version inside plgx - there is a date (build date?) at the beginning of binary, which makes checking version easier from existing file:

577d6a535280cbacb4e4c25ea6dc7409  2017-09-10T21:44:47Z   KeePassRPC.plgx_1.7.3.1 

And I have mono-complete 3.2.8+dfsg-4ubuntu1.1 installed as well. 
Any other hint why plgx is rejected by keepass2 with message:
"A newer KeePass version is required to open this file."

**Comment by marvinwankersteen** [comment]
Same problem on Linux Mint 18.3
- Keepass2 2.32+dfsg-1
- KeePassRPC.plgx 1.7.3
- mono-complete 4.2.1.102+dfsg2-7ubuntu4

I already tried it with the keepass2 version 2.38 from the jtaylor PPA but it doesn't work.

**Comment by nailyk-fr** [comment]
Can you please ensure those packages are installed: https://github.com/kee-org/KeeFox/issues/148#issuecomment-17441227 ?

**Comment by marvinwankersteen** [comment]
I installed `mono-dmcs 4.2.1.102+dfsg2-7ubuntu4` but it still doesn't work.
`libmono-system-management4.0-cil` was already installed with version `4.2.1.102+dfsg2-7ubuntu4`

**Comment by dlech** [comment]
It looks like that comment is out of date. For xenial:

> Depends: keepass2 (>= 2.34), mono-dmcs, libmono-system-management4.0-cil, libmono-system-numerics4.0-cil

For Mint users, I think the difference is that Mint , unlike Ubuntu, passes `--no-install-recommends` to `apt` by default, so make sure when installing any of these packages to also install the recommended packages.

**Comment by marvinwankersteen** [comment]
The three pakets are already installed. But now I tried again keepass2 `2.38+dfsg-1~ubuntu16.04~ppa1` and it works.
Thanks for your help!

**Comment by luckyrat** [comment]
I've added more information to the [troubleshooting docs](https://forum.kee.pm/t/troubleshooting/560#heading--keepass-plugin-could-not-be-loaded) on the community forum which should help resolve some of the various issues discussed here. If you're still having a problem and that information doesn't help, feel free to open a new topic on the Kee community forum (even if you're using KeeFox or some other KeePassRPC client) to ask for more help or suggest improvements to the troubleshooting docs that could have helped you to solve the issue more quickly.

**Comment by ildar** [comment]
1st, on "troubleshooting docs" :
> The following are the most useful:
> 
> –debug : This puts KeePass into debug mode. Depending on what went wrong, KeePass will tell you where to find a file with debug output, provide useful information in a popup or just output a generic and meaningless message.
> 
> –KPRPCDebug= : Output KeePassRPC plugin debug information to a location of your choosing. E.g.: --KPRPCDebug=c:\temp\kprpc-debug.log

wrong. Note that you published: `–debug` , should be `--debug`. Same with `–KPRPCDebug=`
That must be some forum intelligence+substitution.

**Comment by ildar** [comment]
2nd, further investigation.
the debug output shows:
> error CS0006: Metadata file `System.Configuration.Install.dll` could not be found
> error CS0006: Metadata file `System.Data.dll` could not be found
> error CS0006: Metadata file `System.Management.dll` could not be found

the 1&3 belongs to `mono-extras` package and 2 is obviously `mono-data`. Installing the two packages makes everyone happy.

**Comment by luckyrat** [comment]
Thanks @ildar 

I've fixed the formatting on the troubleshooting page.

With your 2nd comment are you suggesting that these two packages were the only ones missing from the default mono installation on your system? We advise people install mono-complete which should include all packages (potentially only if you enable "recommended" components too but this is very system dependent). Did you try mono-complete and find that these two packages were still missing? If so, more detail about your O/S version might help others in future.

**Comment by ildar** [comment]
`mono-complete` surely solves the problem and should stay the recommended
way. I just commented for those who are curious.

**Comment by deepseven** [comment]
> Installing mono-complete fixed it for me on KeePass2 v2.35 and 1.7.2 on Ubuntu 17.04 with Mono 4.6.2.

Indeed, mono-complete did the trick for me (Ubuntu 18.04, keepass 2.38).
