### ISSUE TITLE
Feature Request: Bring KeePass to front

### ISSUE THREAD

**Issue by stevish-com** [kee-org/keepassrpc#70]
I'm just switching over from ChromeIPass and KeePassHTTP, and am missing some of the features, so I thought I'd ask if you'd consider adding them.

The primary one that's affecting me now is that when I opened a website with a login form with ChromeIPass, but keePass was locked, it would bring KeePass window to the front, effectively showing me that I need to re-enter my password, and giving a convenient method for doing so.

This is by no means a make-or-break feature, but one of the little things that make users like me enjoy the experience of interacting with the software a little more.

**Comment by luckyrat** [comment]
You can do this with the ctrl-shift-2 keyboard shortcut already.

With Kee v3.1 and KeePassRPC v1.9 you'll be able to click a button on the Kee main menu too.

If you still want a more aggressive/automatic master key popup then please post the suggestion on the [community forum](https://forum.kee.pm) for discussion.
