### ISSUE TITLE
Support Duplicate Entry

### ISSUE THREAD

**Issue by Riajyuu** [kee-org/keepassrpc#72]
Here is the reference context:
https://superuser.com/questions/434042/can-i-use-multiple-urls-in-the-url-field-of-keepass

Here is use steam entry, change the URL and checked refer password and username.

Here is how my entry looks like 

![image](https://user-images.githubusercontent.com/16912240/56939475-0fbd2b00-6af8-11e9-9a72-9f4617085a4e.png)
(just ignore the second Steam US entry)

When autofilling through kee addon, it fills {REF:U@I:CDD*********420} for **BOTH** username and password rather than referred ones.

**Comment by JanisEst** [comment]
https://forum.kee.pm/t/placeholder-handling/1100

**Comment by Riajyuu** [comment]
seems make sense. Thx
