### ISSUE TITLE
Not compatible with KeePass 2.42

### ISSUE THREAD

**Issue by a-i-joe** [kee-org/keepassrpc#73]
Running on Windows 10, with the KeePassRPC.plgx was put in-place while using KeePass 2.41, a compatibility error was shown after install KeePass 2.42.

**Comment by Havokdan** [comment]
Its ok for me.

**Comment by chikarcas** [comment]
I have the same issue, not loading the plugin
UPDATE:
Just clearing the cache in the plugins window seems to solve the problem.

**Comment by h2ofranck** [comment]
Hi,
same problem on my Ubuntu 19.04. Resolved by a:
sudo apt install mono-complete

**Comment by luckyrat** [comment]
Please check out all the resources on the [community forum](https://forum.kee.pm) and ask there if you can't find the solution.
