### ISSUE TITLE
Ubuntu 19.04 Disco : Not compatible with KeePass... 

### ISSUE THREAD

**Issue by h2ofranck** [kee-org/keepassrpc#74]
Hi,
problem on my new Ubuntu 19.04: "Not compatible with KeePass 2.41" ...

Resolved by a:
sudo apt install mono-complete

Have a good day.

**Comment by Undone** [comment]
I had the same issue with Fedora 30, installing mono-complete fixed it for me aswell. Thanks for the tip.

**Comment by jljouannic** [comment]
No need to install the full set of dependencies pulled by `mono-complete`.

Here is the the command to install the minimum set of packages needed on Ubuntu 19.04 Disco in order to make the KeePassRPC plugin work:
```
$ sudo apt install mono-mcs libmono-system-numerics4.0-cil libmono-system-management4.0-cil
```

**Comment by olix86** [comment]
Also worked for me on Debian Sid, thanks :)

**Comment by Coruna** [comment]
Exactly what I needed to get things work. Thanks a lot :)

**Comment by luckyrat** [comment]
Resolved per the usual "install the currently correct bits of mono" so I'm closing the issue.
