### ISSUE TITLE
Would anybody add multi-languages Interface support to KeePassRPC?

### ISSUE THREAD

**Issue by efreedev** [kee-org/keepassrpc#78]
As title, I want to translate the KeePassRPC into Chinese, but when I do the translation in src, sometimes  it becomes incompatible  for current version of KeePass. So I hope that someone can make a good method to do the tranlation.
Thank you.

**Comment by luckyrat** [comment]
This is being discussed at https://forum.kee.pm/t/keepassrpc-translation/2930/2
