### ISSUE TITLE
Custom placeholders on Form Field

### ISSUE THREAD

**Issue by Generator** [kee-org/keepassrpc#8]
### Expected behavior  
Insert a custom placeholder on Form Field provided by user or plugin

**Example**  
Name: TOPT  
Id: otp_code  
Value: {TOTP}  
Type: Placeholder

### Actual behavior
There's no any _type_ for custom placeholders

**Comment by luckyrat** [comment]
This is already supported for most custom fields. #30 will also enable it for custom Text fields.
