### ISSUE TITLE
KeePassRPC clears contents of publicSuffixDomainCache.txt

### ISSUE THREAD

**Issue by alxandr3** [kee-org/keepassrpc#80]
Hi,

I'm trying to add a domain override to have Kee match the subdomains of (just) amazon.com and I keep getting "Invalid domain name" error. I noticed that if I manually populate /home/[my-user]/.config/KeePass/publicSuffixDomainCache.txt (which was empty) with the contents from publicsuffix.org, the file gets truncated as soon as I try to add a domain override.

In clear:
(populate publicSuffixDomainCache.txt), then open KeePass -> File -> Database settings -> Kee tab -> Domain override section, click Add -> type in amazon.com, select Hostname radio button ->  Invalid domain name (publicSuffixDomainCache.txt drops to 0 bytes at this point).

I tried populating the list and setting the immutable bit (sudo chattr +i) on the file, restart keepass and test, to no avail. The file obviously doesn't get truncated anymore, but I still get the same error.

I'm running:
Fedora 29
keepass-2.40-1.fc29.x86_64
KeePassRPC 1.9.0 (also tested with 1.8, same result)

Thanks

**Comment by luckyrat** [comment]
Please search and post on the community forum for support: https://forum.kee.pm
