### ISSUE TITLE
More than one Port

### ISSUE THREAD

**Issue by musenbaron** [kee-org/keepassrpc#82]
English below (sorry my English is so bad)
Ich nutze Firefox und TOR-browser und 2x die portable Version. Jedesmalig soll ich RPC neu verknüpfen, wenn ich einen den Browser wechsel.
Könnte man bitte mehrere Verbindungen zulassen
-------
I use Firefox and TOR-browser and 2x the portable version. Every time I change my browser I have to re-link RPC.
Could you please allow multiple connections?

**Comment by luckyrat** [comment]
I'm afraid I don't really understand this issue but perhaps the troubleshooting guide or documentation about KeePassRPC port will help. If not, please search on that community forum and post there if you're still stuck in case others can help.

https://forum.kee.pm/t/troubleshooting/560
https://forum.kee.pm/t/keepassrpc-port/2360
