### ISSUE TITLE
Plugin incompatible with current version of keepass (fix)

### ISSUE THREAD

**Issue by diieg707** [kee-org/keepassrpc#83]
i'm using w7 x64 installed keepassrpc and this error was showing, just installed .net framework 4.5 and it fixed the problem

**Comment by sy6sy2** [comment]
Thank you for the advice!
In my case, Windows 7 64 bit without any update.
I installed this file https://www.microsoft.com/fr-fr/download/details.aspx?id=40779 and it works.
