### ISSUE TITLE
The generated password is automatically filled in

### ISSUE THREAD

**Issue by dai640** [kee-org/keepassrpc#85]
When I registered some forums, or websites, I found that the random password generated by keepass, it does not automatically fill in the password box, you need to manually copy the generated password to the password box. How can I make it automatically fill in the generated password to the password box, just like lastpass, 1password, you can automatically fill in the generated password, no need to manually copy.

![2019-09-19_160707](https://user-images.githubusercontent.com/8486208/65225481-cfd30080-daf7-11e9-9f77-d6d77b8e3816.jpg)

**Comment by luckyrat** [comment]
Please search and post on the community forum for support: https://forum.kee.pm
