### ISSUE TITLE
References not resolved with KeePassRPC v1.9.0.0

### ISSUE THREAD

**Issue by NightDragon1** [kee-org/keepassrpc#87]
Hi!
I'm using KeePass 2.43 (Windows 10, 64Bit), KeePassRPC 1.9.0.0 and Kee 3.2.7.
Since a few weeks i use more and more often the Referencemethod of Keepass to manage my passwords.
I recogniced, that Kee/KeePassRPC doesn't handle it properly. After soem research i learned that until KeePassRPC v.1.8.0.0 it was an issue. 

However I'm using the recent version and KeePassRPC still doesn't resolve it properly.
So I had to switch on the datat base setting for the version before 1.8.0.0.

Is this a new issue or me doing something wrong?

BR,
Rob

**Comment by tloehlein** [comment]
Hi,
I'm having the same problem. The references are not resolved.
But even with 1.8.0.0 it is not working for me.
I guess I will use something else, till this issue has been resolved.

Have a good one,
Tom

**Comment by tloehlein** [comment]
Hi Rob,

I found the solution for this.
You have to enable a setting to let Kee resolve the references.
See https://forum.kee.pm/t/placeholder-handling/1100

I'm not 100% sure why it is disabled by default. I might not fully understand the real risk behind it.
Other plugins behave like this out of the box.

I enabled the setting for the whole database and it is working now.

Best regards,
Tom

**Comment by NightDragon1** [comment]
Hi Tom,

thanks for your solution - now everything works as expected.

BR,
Rob
