### ISSUE TITLE
Kee forgets default database settings (on sync)

### ISSUE THREAD

**Issue by MarkCanada** [kee-org/keepassrpc#88]
I keep setting the "Minimum URL match accuracy" to "Hostname" in the database settings and usually it reverts back to "Domain". The "KeePass Placeholders" setting also defaults back to disabled
It seems to be happening after I edit or add an entry and it syncs with another database (location).

**Comment by luckyrat** [comment]
KeePass can't reliably sync database settings - it's just a limitation of the kdbx format so you have to try adjusting the setting in different database sources until you get lucky. Try with no other plugins and making no other changes to the database to increase the chances of it all working as expected.
