### ISSUE TITLE
Disable/Ignore entire database

### ISSUE THREAD

**Issue by BrainStone** [kee-org/keepassrpc#89]
I would to know if it is possible for KeePassRPC to completely ignore an entire database?

I have a few special databases that contain no entries that are used on the web and therefore I'd like to be able to have KeePassRPC to completely ignore these database.

Only option I see right now is to set the "Kee home group" to an empty group created just for this purpose, though I'd like to avoid that if possible.

**Comment by luckyrat** [comment]
Please see https://forum.kee.pm/t/kee-should-offer-to-only-use-some-databases/567/8
