### ISSUE TITLE
KeepassRPC not working with Windows 10.0.19008 Build 19008

### ISSUE THREAD

**Issue by SolomonHD** [kee-org/keepassrpc#90]
I just updated to 10.0.19008 Build 19008 and it broke KeePassRPC, shows this message 
![image](https://user-images.githubusercontent.com/10504925/67643580-695bb200-f8ef-11e9-8af0-951b5e6ff957.png)

It shows this message even if I run KeePass as Administrator, I've allowed KeePass through the Windows Firewall.

**Comment by ghost** [comment]
I ran into this same issue on Windows 10 Pro 10.0.18362 Build 18362. This messages appears each run of KeePass during initial plugin compilation.

ETA: I'm running KeePass 2.43.

**Comment by uncled1023** [comment]
Same issue.  Started showing up when I updated to build 19033.1

**Comment by viRikaRe** [comment]
Any update on this issue?
I have the same issue when I upgraded to Win10 Pro 2004 (build 19041.264).  Previous Windows version worked fine, I think it was 1903 (18362.836).

KeePass 2.45
KeepassRPC 1.9.0 & 1.10.0 (neither working)

**Comment by viRikaRe** [comment]
Now KeepassRPC works on my computer.  KeePass & KeepassRPC versions remain unchanged, but Windows is upgraded to Win 10 Pro 2004 (build 19041.329).
Not sure if the Windows upgrade fixed it.

**Comment by viRikaRe** [comment]
It's broken again with the same error. Windows version did not change. Don't know why...

**Comment by uncled1023** [comment]
Yup, after most recent windows update, this is broken again.  (20150.rs_prerelease_100612-1734)

**Comment by luckyrat** [comment]
It sounds like this is one or more bugs with Windows or one of its components such as .NET Framework. Feel free to continue suggesting fixes for any affected windows builds but I'm closing this issue since there's nothing specifically actionable for KeePassRPC.
