### ISSUE TITLE
Multi-User Port Change Documentation

### ISSUE THREAD

**Issue by mishbieg** [kee-org/keepassrpc#92]
I was looking for some time to resolve the issue with multiple users. I finally found out, that the port needs to be changed. Can this be added to the Documentation/Installation Guide?
https://forum.kee.pm/t/multiple-user-settings/460
That way other users find the solution faster. Thanks.

**Comment by luckyrat** [comment]
Thanks for the suggestion. I've updated the instructions to point to the existing documentation about the KeePassRPC port.

https://forum.kee.pm/t/installing-kee-with-keepassrpc-for-keepass-password-safe-instructions/23

https://forum.kee.pm/t/keepassrpc-port/2360
