### ISSUE TITLE
FF 72.0.2, KeePass 2.44 and RPC Plugin 1.10.0 cause KeePass to crash

### ISSUE THREAD

**Issue by social-ink** [kee-org/keepassrpc#94]
KeePass starts up minimized to tray, but any hovering over it will cause it to crash. Ctrl Alt K does not work. It keeps crashing.

When the plugin is removed from the plugins folder (Windows 10; Program Files x86) then the KeePass program runs fine.  OR when Kee for FF is disabled as an addon, KeePass runs fine.

**Comment by luckyrat** [comment]
I think this is the same as https://forum.kee.pm/t/ff-72-0-2-keepass-2-44-keefox-3-2-7-and-rpc-plugin-1-10-0-cause-keepass-to-crash/2826/4 so closing.
