### ISSUE TITLE
No homegroup set leads to exception

### ISSUE THREAD

**Issue by unkn0wn-devel0per** [kee-org/keepassrpc#98]
Running current KeePassRPC plugin: 1.10.0

Having no kee homegroup set for a database leads to an exception when using keepass menu entry "add folder":

System.Exception: Could not find requested group. Have you deleted your Kee home group? Set a new one and try again.
   bei KeePassRPC.KeePassRPCService.GetRootPwGroup(PwDatabase pwd, String location)
   bei KeePassRPC.Forms.KeeGroupUserControl.get_Status()
   bei KeePassRPC.Forms.KeeGroupUserControl.UpdateStatus()
   bei KeePassRPC.Forms.KeeGroupUserControl.KeeGroupUserControl_Load(Object sender, EventArgs e)
   bei System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.ControlCollection.Add(Control value)
   bei System.Windows.Forms.TabControl.ControlCollection.Add(Control value)
   bei KeePassRPC.GeneralRPCClientManager.AttachToGroupDialog(KeePassRPCExt plugin, PwGroup group, TabControl mainTabControl)
   bei KeePassRPC.KeePassRPCExt.editGroupFormShown(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnShown(EventArgs e)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by luckyrat** [comment]
Yep, things will break if you delete your Kee home group so don't do that :-)
