### ISSUE TITLE
Feature Request: Enable/Disable databases for search/modification

### ISSUE THREAD

**Issue by unkn0wn-devel0per** [kee-org/keepassrpc#99]
Request already posted here, see "mobilekee":
https://forum.kee.pm/t/multiple-keepass-databases-opened/2942/2

I would prefer databases to be enabled/disabled for search and or modification via database properties respected by KeePassRPC.
The property needs to be stored in the database itself, to ensure it being available for keepass programs/addons on other computers.
In case such property is missing in a database, KeePassRPC must deny access to such database by default.

Thanx.

**Comment by luckyrat** [comment]
I've moved the mobilekee post to an existing topic and responded there:

https://forum.kee.pm/t/kee-should-offer-to-only-use-some-databases/567/8
